"""
Модкль с константными значениями для расчёта
"""

__all__ = ['MAX_RENTAL_BATCH_LIMIT', 'PERFORMANCE_LOG_PREFIX', 'TIME_DECIMALS', 'DEFAULT_RETURN_INDEX_BASE']

MAX_RENTAL_BATCH_LIMIT = 150.0
PERFORMANCE_LOG_PREFIX = "[PERF_LOG]"
TIME_DECIMALS = 8
DEFAULT_RETURN_INDEX_BASE = 10.0